### PR TITLE
fix message truncation issue for strings with embedded nulls

### LINKED ISSUE #51: verification_key_sign_sha512 cannot sign messages with embedded NUL bytes
The signature of this function is:

```
C_VerificationSignature *verification_key_sign_sha512(const C_VerificationKey *key,
                                                      const char *message);
```

And the implement treats `message` as a NUL-terminated string.  Thus, only bytes up to the first NUL can be considered.  In the Python bindings I'm working on/with, a Python string (which always carries its length with it) with an embedded NUL gets quietly truncated here and the "wrong" message is signed.

There doesn't seem to be any reason the underlying Rust implementation can't sign a message with NUL bytes, as long as the message is delivered there intact.

### PR DESCRIPTION
**Pull request by evq**
fixes #51 by no longer passing strings to `verification_key_sign_sha512` and `verification_key_invalid_sha512` with C conventions (null terminated) and instead passing an explicit length

crate version has been bumped as C API has changed, however C++ / Golang APIs provided by the bindings are unchanged

### CODE REVIEW

File: examples/cpp/main.cpp [hunk 1]
```diff
@@ -139,7 +139,7 @@ int main() {
   }
   check_exception();
 
-  if (server_vKey.verify(server_sig, "foobar")) {
+  if (server_vKey.verify(server_sig, std::string("\0foobar", 7))) {
```
Comment (exarkun) [inline examples/cpp/main.cpp:142]: So if the bug were present, the `sign` call above would sign a zero-length message and this `verify` call would verify the signature of a zero-length message and verification would succeed.  With the bug fixed, the signature is now really of `"\0test message"` and the verification is against `"\0foobar"` - so the verify fails because the messages aren't the same.

Cool.

File: examples/golang/main.go [hunk 2]
```diff
@@ -103,7 +103,7 @@ func main() {
 	}
 
 	// server signs the wrong message using the shared key and compares the client signature to it's own
-	result, err = servervKey.Verify(clientSig, "message")
+	result, err = servervKey.Verify(clientSig, "\x00message")
```
Comment (exarkun) [inline examples/golang/main.go:106]: And again here, as in the C++ example.

**Review by exarkun — COMMENTED** [review]
Cool.  I hardly know Rust so I can't say much but I think I get the idea of this change and it seems like the right direction to me.  One thing I notice here is that though the fix is being applied pretty much all the way across the API, the test coverage only seems to cover handling of the message for signing and verification (so, eg, it looks to me like unmarshalling a batch dleq proof now handles an embedded nul gracefully but I don't see any test coverage for this).

**Comment by evq** [comment]
Right - we figured would be best to accept strings with a length across the board, which meant updating the base64 decode functions.

Since we're expecting base64 input there isn't really a valid reason for there to be an embedded null - so adding the length there is more for additional safety e.g. in case a user accidentally passes a non null-terminated string.

**Comment by exarkun** [comment]
Is further progress on this blocked on me?

**Comment by evq** [comment]
Not at all @exarkun. Sorry for the delay. We had an initial round of internal review on this PR but it unfortunately dropped off our radar after that. I will re-raise for review so we can get this fix merged in.

Thanks for your patience and the check-in!

File: src/lib.h [hunk 3]
```diff
@@ -99,7 +99,7 @@ typedef struct C_VerificationSignature C_VerificationSignature;
  * If something goes wrong, this will return a null pointer. Don't forget to
  * destroy the returned pointer once you are done with it!
  */
-C_BatchDLEQProof *batch_dleq_proof_decode_base64(const char *s);
+C_BatchDLEQProof *batch_dleq_proof_decode_base64(const uint8_t *s, uintptr_t s_length);
```
Comment (isislovecruft) [inline src/lib.h:102]: Passing pointers and lengths was also how we handled FFI between Rust and C in tor.

File: src/lib.rs [hunk 4]
```diff
@@ -25,14 +25,14 @@ type HmacSha512 = Hmac<Sha512>;
 
 #[cfg(not(feature = "cbindgen"))]
 thread_local! {
-    static LAST_ERROR: RefCell<Option<Box<Error>>> = RefCell::new(None);
+    static LAST_ERROR: RefCell<Option<Box<dyn Error>>> = RefCell::new(None);
```
Comment (isislovecruft) [inline src/lib.rs:28]: Out of sheer curiosity because I've never had a chance to use it yet, why is this now dynamically dispatched? Was a new `Error` impl added and now they need to be interchangeable?

**Review by isislovecruft — APPROVED** [review]
Looks good to me!

File: src/lib.rs (hunk 4 above)
Comment (evq) [reply src/lib.rs:28]: This was just to fix a warning: https://github.com/brave-intl/challenge-bypass-ristretto-ffi/issues/55

I think the underlying behavior is unchanged - trait objects were always dynamically dispatched, it's just that the syntax was changed to be more explicit:
https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html

It's been a while, but I think I used a trait object here since I just was being a bit lazy and wanted to avoid having to define a new top level error type in this FFI crate lol.

In general I'm pretty unsatisfied with the approach I took for error handling here. It's all too easy to forget about checking for errors when we're using it in practice within Chromium ( where we don't end up raising exceptions. ) I think if I were to do this again I might define the top level "result" enum ( Ok + all error variants ) with `#[repr(C)]`, passing it across the C FFI and use cbindgen to generate a matching enum definition in the C header. That at least matches the C++ error handling we're doing elsewhere - a far cry from rust, but what can you do. ¯\\_(ツ)_/¯
